### ISSUE TITLE
Check which integration can be done if NGS runs inside docker

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#188]

**Comment by zglozman** [comment]
I really think the name of the issue is misleading. But the upshot of the feature would be:
# General Idea  

```
container = Docker:Container("alpine:3.2"), [
DOCKER:Container:withExposedPorts(80)
DOCKER:Container:withAutoStart()
DOCKER:Container:withEnv("MAGIC_NUMBER", "42")
DOCKER:Container:withCommand("/bin/sh", "-c", 
"while true; do echo \"$MAGIC_NUMBER\" | nc -l -p 80; done")]
```
# 1. Creating Containers:
*``container = Docker::Container("redis:5.0" )`` 
# 2. Managing Container Properties:
* ``a.withCommand("redis-server --port 7777")``
* ``a.withEnv("API_TOKEN", "foo")``
# 3. Exec Commands
*``res = container.execInContainer("touch", "/somefile.txt"); //Parse needs to be disgined. ``

# 4. Attachment of resources 
```
container .withClasspathResourceMapping("redis.conf",
                                      "/etc/redis.conf",
                                      BindMode.READ_ONLY)
```

# 5. Waiting and Binding
````container.forHttp("/", [StatusCode(200),  StatusCode(301)])````

# 6. Logs
```logs = a.getLogs().lines().each(F(x) echo(x));```

**Comment by ilyash-b** [comment]
> I really think the name of the issue is misleading.

Nope. This issue is really about language features that will facilitate running NGS programs *inside Docker*.

What you are suggesting is a *Docker library*, which should probably be similar to AWS library. Your proposal should be moved to separate issue.

**Comment by ilyash-b** [comment]
No real use cases seen until now. Additionally, programs running in a container should run "as usual" by design. Closing.
