### ISSUE TITLE
[feature] Scoped multimethods

### ISSUE THREAD

**Issue by hexagonrecursion** [ngs-lang/ngs#458]
Multimethods are awesome because sometimes you do want to shoot every foot in the building. Unfortunately sometimes they are too powerful because you only want to shoot your own left pinkie toe and nothing else.

Example:
* A program foobar exits with a nonzero code even when no errors occurred
* Alice is fed up with sprinkling her code with explicit exit code handling and wants to handle this once and for all

Currently the only tool Alice has is the finished_ok multimethod, but adding a new method to an existing multimethod risks violating assumptions other unrelated code makes. What Alice really wants is to only change the behavior of finished_ok for command invocations she does herself.

One possible extension of the current multimethod semantics is to allow methods to be dynamically added and removed from a multimethod. Alice could then write code to:
1. Add a method to finished_ok
2. Run foobar
3. Remove the method

This runs into a problem: other unrelated code may be invoked between 1 and 3 and its assumptions will be violated

Another possible extension is to rely on lexical scope and call different methods depending on the source location of the call. This could be useful sometimes but is not powerful enough for Alice because she is not calling finished_ok directly.

I think I know a solution to this riddle, but I need more thinking. Also I'm busy today. Will write more soon [tm]

**Comment by ilyash** [comment]
While you are thinking, here are few items from the top of my head about this:

> Multimethods are awesome because sometimes you do want to shoot every foot in the building. Unfortunately sometimes they are too powerful because you only want to shoot your own left pinkie toe and nothing else.

That's why in my mind, it's best to add methods (to multimethods) that handle your own types or your own situation.

> Currently the only tool Alice has is the finished_ok multimethod, but adding a new method to an existing multimethod risks violating assumptions other unrelated code makes. What Alice really wants is to only change the behavior of finished_ok for command invocations she does herself.

For me, there is something off here. In my mind, if you add your own `finished_ok()`, it should be specific to a command and not specific to where you call that external program from. I can't imagine an external program called let's say `p1` which should cause exception for exit code `N` depending on who called it. So:

    F finished_ok(p:Process) {
        guard p.command.argv[0] == "my_snowflake"
        CUSTOM_LOGIC
    }



> Alice is fed up with sprinkling her code with explicit exit code handling and wants to handle this once and for all

Note that in NGS, it is not nearly as bad as in other languages. That amounts to prefixing a program with `ok:...` like `ok:1..10 my_snowflake`. See examples at https://github.com/ngs-lang/ngs/blob/cb86ec068751d066217fb003ab0d3124e823455e/lib/stdlib.ngs#L5437-L5441

**Comment by ilyash** [comment]
Please reopen if you have new ideas or use cases
