### ISSUE TITLE
Add exec()

### ISSUE THREAD

**Issue by hexagonrecursion** [ngs-lang/ngs#459]
Most shells have the ability to replace the current process:
```bash
#!/usr/bin/env bash
exec foobar
```
One example where this is useful is a container entrypoint:
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint

> This script uses the exec Bash command so that the final running application becomes the container’s PID 1. This allows the application to receive any Unix signals sent to the container.

I searched [your documentation](https://ngs-lang.org/doc/latest/man/ngslang.1.html) for the word "exec" and found nothing.

**Comment by ilyash** [comment]
There is no "high level" `exec()` method exposed in NGS. It should be added, since it's a perfectly valid use case for NGS (related #188 - Check which integration can be done if NGS runs inside docker).

NGS has two "layers" when exposing OS (and other) APIs

* Exposing low level API into the language. Many C functions are exposed as `c_...` functions.
* Standard library wraps the low level APIs into something that is nice to work with (exceptions, better API, etc)

Right now, there is `c_execve()`, which you can use to test things. https://ngs-lang.org/doc/latest/generated/c_execve.html ( corresponds to https://man7.org/linux/man-pages/man2/execve.2.html )

`c_execve` is used by the standard library to implement `$(...)` and friends so you can see an example here - https://github.com/ngs-lang/ngs/blob/cb86ec068751d066217fb003ab0d3124e823455e/lib/stdlib.ngs#L5795-L5798

Here is TODO as I see it: provide `exec()` in standard library.

**Comment by ilyash** [comment]
In `dev` branch. Closing. Reopen if expectations are not met (describe please). Also reopen if you prefer to work with released versions. I'll close this issue when the feature is released then.
